import type { Dress } from './types';
import { PlaceHolderImages } from './placeholder-images';

const dressImages = PlaceHolderImages.filter(img => img.id.startsWith('dress-'));

export const vestidos: Dress[] = [
  {
    id: '1',
    nombre: 'Blusa "Bembella White"',
    modelo: 'Bembella White',
    marca: 'Malva Department Store',
    precio: 120,
    image: dressImages.find(i => i.id === 'dress-1')!,
    shortDescription: 'Blusa cruzada blanca, juvenil y versátil.',
    descripcion:
      '¡Descubre la elegancia casual con la Blusa “Bembella White” de Malva Department Store! Diseñada para resaltar tu figura con un toque moderno y femenino, esta blusa cruzada de manga larga es ideal para outfits urbanos o salidas de día. Su color blanco y su detalle ajustable en la cintura la hacen una prenda versátil que combina fácilmente con jeans, faldas o pantalones de vestir.',
    tipo: 'Blusa cruzada',
    genero: 'Mujer',
    fit: 'Ajustado al cuerpo con amarre lateral',
    material: 'Algodón con elastano',
    composicion: '95% algodón, 5% elastano',
    temporada: 'Primavera / Verano',
    largo_mangas: 'Manga larga',
    diseno: 'Liso con detalle de lazo lateral',
    estilo: 'Casual / Chic',
    hecho_en: 'Perú',
    condicion: 'Nuevo',
    tallas: ['S', 'M', 'L'],
    colores: ['Blanco'],
    contactPhone: '51932380544'
  },
  {
    id: '2',
    nombre: 'Blusa "Bembella Black"',
    modelo: 'Bembella Black',
    marca: 'Malva Department Store',
    precio: 180,
    image: dressImages.find(i => i.id === 'dress-2')!,
    shortDescription: 'Versión en negro de la Bembella.',
    descripcion: '¡Resalta tu elegancia con la Blusa "Bembella Black" de Malva Department Store! Esta prenda combina sofisticación y comodidad, perfecta para looks de noche o eventos especiales. Su diseño off shoulder (hombros descubiertos) y el drapeado en la parte superior realzan tu silueta con un toque moderno y femenino. Ideal para combinar con pantalones de vestir, faldas o jeans, logrando un estilo elegante y versátil.',
    tipo: 'Blusa off shoulder',
    genero: 'Mujer',
    fit: 'Ajustado al cuerpo',
    material: 'Poliéster con elastano',
    composicion: '95% poliéster, 5% elastano',
    temporada: 'Otoño / Invierno',
    largo_mangas: 'Manga larga',
    diseno: 'Liso con pliegues drapeados',
    estilo: 'Elegante / Chic',
    hecho_en: 'Perú',
    condicion: 'Nuevo',
    tallas: ['S', 'M', 'L'],
    colores: ['Negro'],
    contactPhone: '51932380544'
  },
  {
    id: '3',
    nombre: 'Blusa "Malva"',
    modelo: 'Malva',
    marca: 'Malva Department Store',
    precio: 150,
    image: dressImages.find(i => i.id === 'dress-3')!,
    shortDescription: 'Blusa con estilo Malva.',
    descripcion: '¡Eleva tu estilo con la Blusa "Malva" de Malva Department Store! Su diseño delicado y romántico combina detalles de encaje con una silueta femenina que realza la figura. Con escote en "V", botones frontales y vuelo en la parte baja, esta blusa es perfecta para ocasiones especiales o para un look elegante de día. Su color blanco y su textura ligera aportan frescura y un toque sofisticado a cualquier outfit.',
    tipo: 'Blusa con vuelo y encaje',
    genero: 'Mujer',
    fit: 'Corte ceñido en la cintura con caída suelta',
    material: 'Algodón con detalles de encaje',
    composicion: '90% algodón, 10% poliéster',
    temporada: 'Primavera / Verano',
    largo_mangas: 'Sin mangas',
    diseno: 'Escote en "V" con borde de encaje y botones frontales',
    estilo: 'Romántico / Elegante',
    hecho_en: 'Perú',
    condicion: 'Nuevo',
    tallas: ['S', 'M', 'L'],
    colores: ['Blanco'],
    contactPhone: '51932380544'
  },
  {
    id: '4',
    nombre: 'Blusa "Matchy"',
    modelo: 'Matchy',
    marca: 'Malva Department Store',
    precio: 95,
    image: dressImages.find(i => i.id === 'dress-4')!,
    shortDescription: 'Estilo matchy para combinaciones fáciles.',
    descripcion: 'Atrévete a destacar con la Blusa "Matchy" de Malva Department Store. Diseñada para las que aman los looks atrevidos y modernos, esta blusa de estilo off shoulder combina transparencia, textura y estampado artístico. Su tela ligera y elástica se adapta al cuerpo, resaltando la silueta con un toque urbano y vanguardista. Ideal para salidas nocturnas, conciertos o combinar con prendas básicas para un look casual con mucha actitud.',
    tipo: 'Blusa off shoulder transparente',
    genero: 'Mujer',
    fit: 'Ajustado al cuerpo',
    material: 'Malla elástica',
    composicion: '92% poliéster, 8% elastano',
    temporada: 'Otoño / Verano',
    largo_mangas: 'Manga larga',
    diseno: 'Estampado abstracto con efecto translúcido',
    estilo: 'Urbano / Streetwear',
    hecho_en: 'Perú',
    condicion: 'Nuevo',
    tallas: ['S', 'M', 'L'],
    colores: ['Variante'],
    contactPhone: '51932380544'
  },
  {
    id: '5',
    nombre: 'Blusa "Topp"',
    modelo: 'Topp',
    marca: 'Malva Department Store',
    precio: 135,
    image: dressImages.find(i => i.id === 'dress-5')!,
    shortDescription: 'Blusa Topp de corte moderno.',
    descripcion: '¡Sencilla, moderna y con mucho estilo! La Blusa "Topp" de Malva Department Store es el básico ideal para crear looks versátiles y frescos. Su diseño tipo crop top de tiras delgadas resalta la figura y brinda comodidad gracias a su material elástico y suave. Perfecta para combinar con jeans de tiro alto, pantalones wide leg o faldas, logrando un look casual y atractivo para cualquier ocasión.',
    tipo: 'Blusa crop de tiras',
    genero: 'Mujer',
    fit: 'Ajustado al cuerpo',
    material: 'Lycra satinada',
    composicion: '90% poliéster, 10% elastano',
    temporada: 'Verano / Primavera',
    largo_mangas: 'Sin mangas (tirantes delgados)',
    diseno: 'Liso, corte recto y acabado brillante',
    estilo: 'Casual / Minimalista',
    hecho_en: 'Perú',
    condicion: 'Nuevo',
    tallas: ['S', 'M', 'L'],
    colores: ['Variante'],
    contactPhone: '51932380544'
  },
  {
    id: '6',
    nombre: 'Blusa "Bembella Red"',
    modelo: 'Bembella Red',
    precio: 135,
    image: dressImages.find(i => i.id === 'dress-7')!,
    shortDescription: 'Versión roja de Bembella.',
    tipo: 'Blusa',
    genero: 'Mujer',
    tallas: ['S', 'M', 'L'],
    colores: ['Rojo']
  },

];
