import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { lusitana } from '@/app/components/fonts';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lusitana.className} antialiased min-h-screen flex flex-col`}>

        {children}
      </body>
    </html>
  );
}
